export const NOT_PLANNED_COLOR = 'text-gray-400 border-gray-500/30 bg-gray-500/10';
export const NOT_PLANNED_LABEL = 'NOT PLANNED';

export const CATEGORIES = [
  { id: 'core', label: 'Core VM & AIR', icon: '◫' },
  { id: 'interfaces', label: 'Interfaces', icon: '⌘' },
  { id: 'onchain', label: 'On-Chain & Trust', icon: '⛓' },
  { id: 'gaps', label: 'Language & Execution Gaps', icon: '↻' },
  { id: 'not-planned', label: 'Explicitly Not Planned', icon: '⊘' },
];

export const ITEMS = [
  {
    id: 1,
    category: 'core',
    title: 'Accumulator + register ISA',
    desc: 'INIT/ADD/SUB/MUL, forward-only JZ/JNZ, LOAD/STORE across 4 fixed registers -- a real interpreter and a .zkasm assembly format.',
    status: 'implemented',
    detail: 'crates/zkvm-isa. See the .zkasm Spec for the complete instruction table and the exact forward-jump error string.',
    link: '/zkasm-spec',
  },
  {
    id: 2,
    category: 'core',
    title: 'STARK proof via Winterfell',
    desc: 'A from-scratch AIR binding a proof to one exact program and its actual execution. Real proof, ~11 KB, ~5.5ms to verify.',
    status: 'implemented',
    detail: 'crates/zkvm-stark::prove_program / verify_program. See Architecture for the full transition/boundary constraint walkthrough.',
    link: '/architecture',
  },
  {
    id: 3,
    category: 'core',
    title: 'No-secret-witness soundness design',
    desc: 'Because the program and inputs are fully public, the verifier re-executes and asserts almost everything directly -- no lookup or permutation argument needed.',
    status: 'implemented',
    detail: 'This is this project\'s own term for the design, not standard vocabulary. See the glossary entry for where it stops applying (private inputs, dynamic addressing).',
    link: 'https://www.zkvm.host/glossary/no-secret-witness/',
    external: true,
  },
  {
    id: 4,
    category: 'core',
    title: 'One-hot selectors instead of a mux',
    desc: 'Seven opcode-selector columns and a register selector, multiplied algebraically instead of using a lookup/mux gadget.',
    status: 'implemented',
    detail: 'See the "registers without a mux" post for the full technique.',
    link: 'https://www.zkvm.host/blog/registers-without-a-mux/',
    external: true,
  },
  {
    id: 5,
    category: 'interfaces',
    title: 'CLI: run / prove / verify / deploy / demo',
    desc: 'Five subcommands, one binary. deploy pushes a program to a running zkvm-host-server and verifies the returned proof locally.',
    status: 'implemented',
    detail: 'crates/zkvm-cli. Exact usage strings and sample output on the CLI Reference page.',
    link: '/cli-reference',
  },
  {
    id: 6,
    category: 'interfaces',
    title: 'Hardened HTTP proving API',
    desc: '1 MB body limit, 60s timeout, 4 concurrent requests, and a 2,000-instruction ceiling derived from real measured proving times.',
    status: 'implemented',
    detail: 'crates/zkvm-host-server. Every route and exact request/response shape on the API Reference page.',
    link: '/api-reference',
  },
  {
    id: 7,
    category: 'interfaces',
    title: 'MCP server (prove / verify tools)',
    desc: 'Real prove/verify MCP tools, verified against an actual initialize -> tools/list -> tools/call handshake, on their own port.',
    status: 'implemented',
    detail: "Runs on port 4478, not nested on the HTTP API -- rmcp's StreamableHttpService doesn't nest cleanly onto axum::Router.",
    link: '/mcp',
  },
  {
    id: 8,
    category: 'onchain',
    title: 'ProofOrchestrator + AttestedVerifier',
    desc: 'A task/reward lifecycle contract with zero verification logic of its own, plus an explicit, documented trust-bridge verifier.',
    status: 'implemented',
    detail: 'AttestedVerifier checks an ECDSA signature from one designated attester key over the claimed result -- not the STARK proof itself.',
    link: '/contracts',
  },
  {
    id: 9,
    category: 'onchain',
    title: 'UnimplementedStarkVerifier',
    desc: 'Reverts, always -- the honest state of "no real on-chain verifier exists yet," instead of a stub that quietly returns true.',
    status: 'implemented',
    detail: 'Doing this insecurely would silently accept invalid proofs, strictly worse than an explicit trust assumption.',
    link: '/contracts',
  },
  {
    id: 10,
    category: 'onchain',
    title: 'Foundry test suite',
    desc: '8 real tests: the unimplemented verifier makes payout impossible, the attested happy path, and every failure mode (wrong proof, wrong caller, double-fulfillment, unclaimed tasks).',
    status: 'implemented',
    detail: 'contracts/test/ProofOrchestrator.t.sol, run on every PR via CI.',
    link: '/ci',
  },
  {
    id: 11,
    category: 'onchain',
    title: 'A real trustless on-chain STARK verifier',
    desc: 'Five pieces needed: Fiat-Shamir recompute (Keccak, not Blake3), Merkle authentication, FRI verification, field arithmetic in Solidity/Yul, and the out-of-domain constraint check.',
    status: 'roadmap',
    detail: "None of these five are built. AttestedVerifier is the honest stand-in until they are.",
    link: '/onchain-verifier',
  },
  {
    id: 12,
    category: 'onchain',
    title: 'Recursive proof compression / SNARK wrapping',
    desc: 'The path to genuinely cheap, trustless on-chain verification -- proving the STARK verifier\'s own execution with a SNARK.',
    status: 'research',
    detail: 'docs/RECURSION.md is a scoped literature review, not an implementation. Verdict: a real 2-3 month project, nothing started.',
    link: '/recursion',
  },
  {
    id: 13,
    category: 'gaps',
    title: 'Loops (backward jumps)',
    desc: 'JZ/JNZ can only jump forward today. Real loops need a dynamically-sized, bounded execution trace.',
    status: 'roadmap',
    detail: 'First item in the real "suggested next slice" ordering -- most validation-per-effort of the three gaps.',
    link: '/roadmap',
  },
  {
    id: 14,
    category: 'gaps',
    title: 'Addressable memory',
    desc: 'LOAD/STORE address one of four statically-named registers, not a runtime-computed address.',
    status: 'roadmap',
    detail: "Open question: does the no-secret-witness trick still work once addresses are dynamic, or is a real permutation argument required?",
    link: '/roadmap',
  },
  {
    id: 15,
    category: 'gaps',
    title: 'RV32I compatibility',
    desc: 'A standard RISC-V subset instead of the custom .zkasm ISA.',
    status: 'roadmap',
    detail: 'Deliberately last in the real ordering -- only worth pursuing once loops and memory are solid.',
    link: '/roadmap',
  },
  {
    id: 16,
    category: 'not-planned',
    title: 'Formal verification, fuzzing, external audit',
    desc: 'The only soundness evidence today is this repo\'s own unit test suite.',
    status: 'not-planned',
    detail: 'Named plainly in docs/ROADMAP.md as a real gap, not glossed over.',
    link: '/security',
  },
  {
    id: 17,
    category: 'not-planned',
    title: 'GPU/ASIC performance work',
    desc: 'Blake3_256 and a 128-bit field with default parameters were chosen for correctness first, not speed.',
    status: 'not-planned',
    detail: 'Real measured numbers exist (~1.2s at 1,000 instructions, ~32s at 4,000) -- optimizing them is simply not in scope yet.',
    link: '/benchmarks',
  },
  {
    id: 18,
    category: 'not-planned',
    title: 'A second real proving backend',
    desc: 'SP1 was specifically investigated and declined.',
    status: 'not-planned',
    detail: '518 resolved dependencies, a Go FFI requirement, and an ISA mismatch -- the concrete reasons were written down, not silently dropped.',
    link: 'https://www.zkvm.host/blog/why-not-sp1/',
    external: true,
  },
  {
    id: 19,
    category: 'not-planned',
    title: 'Auth on the HTTP or MCP surfaces',
    desc: 'Both are local/trusted-network use only, on purpose, today.',
    status: 'not-planned',
    detail: 'Named explicitly in docs/THREAT_MODEL.md as a real limitation, not an oversight.',
    link: '/threat-model',
  },
  {
    id: 20,
    category: 'not-planned',
    title: 'Token, marketplace, decentralized prover network',
    desc: 'No token, no proving marketplace, no cross-chain bridges -- none of it has a code artifact anywhere in this repo.',
    status: 'not-planned',
    detail: 'This is the single most common inflated claim in zkVM marketing generally. This project makes none of them.',
    link: '/faq',
  },
];
